name: Email Step Action

on:
  push:
    branches:
      - main  # or whichever branch you want to use

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 24ds2000083@ds.study.iitm.ac.in
        run: echo "Hello, world!"
